build:
  system_packages:
    - "ffmpeg"
  python_packages:
    - "librosa==0.10.1"
    - "torch==2.1.0"
    - "accelerate==0.31.0"
    - "transformers==4.41.1"
    - "hf-transfer==0.1.9"
    - "huggingface-hub==0.27.1"
